### ISSUE TITLE
Duplicate context_processor in settings.py

### ISSUE THREAD

**Issue by amirsoroush** [wsvincent/djangoforapis#114]
https://github.com/wsvincent/restapiswithdjango/blob/4a12e5289beeb00308f2d8ceefa343666fa11c05/ch8-blog-user-auth/django_project/settings.py#L79

Hi,
In [`ch8-blog-user-auth/django_project/settings.py`](https://github.com/wsvincent/restapiswithdjango/blob/4a12e5289beeb00308f2d8ceefa343666fa11c05/ch8-blog-user-auth/django_project/settings.py) file, `"django.template.context_processors.request",` is duplicate.
Thanks.

**Comment by wsvincent** [comment]
Yup, Correct. Nice catch @amirsoroush. Belatedly updating the book/course now for Django 5.1+. Thank you for taking the time to point this out.
